# -*- coding: utf-8 -*-
"""pregunta4 M3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HgvdC-MVMhn-0FUKE8caCvN3Nw7UyxVl
"""

class Vehicle:
    def __init__(self, name):
        self.name = name

    def move(self):
        print("El vehículo se está moviendo")

class Car(Vehicle):
    def __init__(self, name, max_speed):
        super().__init__(name)
        self.max_speed = max_speed

    def move(self):
        print(f"El coche está moviéndose a una velocidad máxima de {self.max_speed} km/h")


my_car = Car(name="Toyota", max_speed=180)


my_car.move()