# -*- coding: utf-8 -*-
"""pregunta 1 M3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jXbIQWExAdBhvxkWidR0WNYXdLqW-6Wb
"""

def divide_numbers(numerator,denominator):


  if denominator == 0:
    return print("nose puede dividir * cero")

  else: return numerator//denominator

divide_numbers(15,0)