# -*- coding: utf-8 -*-
"""pregunta 3 M3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JBw0w-4fFNMMEc8rJeMnQEe47gUkvqG0
"""

class BankAccount:
    def __init__(self):

        self.__balance = 0

    def deposit(self, amount):

        if amount > 0:
            self.__balance += amount
        else:
            print("El monto del depósito debe ser positivo.")

    def withdraw(self, amount):

        if amount > 0:
            if amount <= self.__balance:
                self.__balance -= amount
            else:
                print("Saldo insuficiente para retirar la cantidad solicitada.")
        else:
            print("El monto del retiro debe ser positivo.")

    def get_balance(self):

        return self.__balance


account = BankAccount()


account.deposit(100)


account.withdraw(50)


account.withdraw(100)

print("Saldo actual:", account.get_balance())