# -*- coding: utf-8 -*-
"""pregunta 6 M3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Em5VA2tDAtr3ik_YMsNewqN0pmvHBXQl
"""

!pip install pandas

import pandas as pd


data = {
    'Ciudad': ['Ciudad A', 'Ciudad B', 'Ciudad C', 'Ciudad A', 'Ciudad B', 'Ciudad C'],
    'Tipo Incidente': ['Robo', None, 'Accidente', 'Robo', 'Incendio', None]
}

df = pd.DataFrame(data)


df['Tipo Incidente'].fillna('Desconocido', inplace=True)


conteo_incidentes = df['Tipo Incidente'].value_counts()


print(conteo_incidentes)