# -*- coding: utf-8 -*-
"""Pregunta 5 M3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1165f16X10YAywAWzAYEOiyDNJhnNnYl5
"""

!pip install pandas

import pandas as pd

Año = [2005,2019,2014,2000,2022]
Accidentes = [5,3,25,9,300]

tabla ={
    "Año": Año,
    "Accidentes": Accidentes
}

tabla

df = pd.DataFrame(tabla)
df

df

df_años = df.copy()

df_años = df_años.sort_values(by=['Año', 'Accidentes'])

print("Año y Accidentes:")
print(df_años)

df_accidentes = df_años.copy()

total_accidentes = df_accidentes['Accidentes'].sum()

print(f"Total de accidentes en 5 años es: {total_accidentes}")